apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
  creationTimestamp: "2021-02-07T09:03:37Z"
  generation: 6
  labels:
    app: nginx-1
  name: nginx-1
  namespace: default
  resourceVersion: "88961"
  selfLink: /apis/apps/v1/namespaces/default/deployments/nginx-1
  uid: 5b3e05ce-516c-4986-b70a-6c012aec86ac
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-1
    spec:
      containers:
      - image: gcr.io/voltaic-triode-303809/hello-app:v5.1
        imagePullPolicy: IfNotPresent
        name: hello-app-sha256-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2021-02-07T09:03:40Z"
    lastUpdateTime: "2021-02-07T09:03:40Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-02-07T09:03:37Z"
    lastUpdateTime: "2021-02-07T12:30:50Z"
    message: ReplicaSet "nginx-1-855d9c5d74" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 6
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
