apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-1
  name: nginx-1-service
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx-1
  sessionAffinity: None
  type: LoadBalancer
